name: autopep8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8 pycodestyle
    - name: Run autopep8
      run: |
        pycodestyle ./discord/ext/ | cut -d: -f1 | sort | uniq | xargs autopep8 -i
    - name: push
      run: |
        git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        if (git diff --shortstat | grep '[0-9]'); then \
          git add .; \
          git commit -m "GitHub Actions から差分を Push"; \
          git push origin HEAD:${GITHUB_REF}; \
        fi
